CREATE TABLE login(
    id INT AUTO INCREMENT PRIMARY KEY NOT NULL,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(30) NOT NULL
);

CREATE TABLE loginpage(
    id INT AUTO INCREMENT PRIMARY KEY NOT NULL,
    name VARCHAR(30) NOT NULL,
    address TEXT NOT NULL,
    date_of_event VARCHAR(30) NOT NULL
);